"""
Merge multiple Roboflow YOLO exports into the 4-class detection dataset used by the app.

This is meant for the current workflow where one Roboflow project contains
Binh_Thuong/Nam_Tay/Chi_Ngon_Tro images labeled as "hand", and another project
contains Xoe_Tay images labeled as "hand".

The script infers the real gesture class from filenames, remaps class ids to:
  0 Binh_Thuong
  1 Nam_Tay
  2 Chi_Ngon_Tro
  3 Xoe_Tay

It also converts YOLO segmentation polygon labels to YOLO detection bbox labels.

Run:
  python training/04_merge_roboflow_exports.py --clean --zip-output dataset.zip
"""

from __future__ import annotations

import argparse
import random
import re
import shutil
import zipfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_SOURCES = [
    BASE_DIR / "data" / "roboflow_export" / "LaTuan.v1i.yolov8",
    BASE_DIR / "data" / "roboflow_export" / "LaTuan.v1i.yolov8 (1)",
]
DEFAULT_DATASET_DIR = BASE_DIR / "dataset"

CLASS_IDS = {
    "Binh_Thuong": 0,
    "Nam_Tay": 1,
    "Chi_Ngon_Tro": 2,
    "Xoe_Tay": 3,
}
CLASS_NAMES = ["Binh_Thuong", "Nam_Tay", "Chi_Ngon_Tro", "Xoe_Tay"]
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

DATA_YAML = """# Generated by training/04_merge_roboflow_exports.py
path: /content/dataset
train: images/train
val: images/val

names:
  0: Binh_Thuong
  1: Nam_Tay
  2: Chi_Ngon_Tro
  3: Xoe_Tay
"""


@dataclass(frozen=True)
class ImageRecord:
    image_path: Path
    label_path: Path
    class_name: str
    group_key: str
    source_slug: str


@dataclass
class ConvertStats:
    bbox_lines: int = 0
    polygon_lines: int = 0
    empty_labels: int = 0
    skipped_lines: int = 0


def normalize_name(value: str) -> str:
    return value.lower().replace("-", "_").replace(" ", "_")


def infer_class(path: Path) -> str | None:
    name = normalize_name(path.name)
    if "binh_thuong" in name or name.startswith("normal"):
        return "Binh_Thuong"
    if "nam_tay" in name or name.startswith("fist"):
        return "Nam_Tay"
    if "chi_ngon" in name or "chi_ngon_tro" in name or name.startswith("point"):
        return "Chi_Ngon_Tro"
    if "xoe_tay" in name or "open_hand" in name:
        return "Xoe_Tay"
    return None


def source_slug(source: Path) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", source.name).strip("_").lower()
    return slug or "source"


def original_group_key(image_path: Path, class_name: str) -> str:
    stem = image_path.stem
    # Roboflow filenames often look like:
    # binh_thuong_00000_jpg.rf.<hash>.jpg
    match = re.match(r"(.+?)_(jpg|jpeg|png|bmp|webp)\.rf\.", stem, flags=re.IGNORECASE)
    if match:
        stem = match.group(1)
    stem = re.sub(r"[^A-Za-z0-9_]+", "_", stem).strip("_").lower()
    return f"{class_name}:{stem}"


def label_for_image(image_path: Path) -> Path:
    parts = list(image_path.parts)
    for index, part in enumerate(parts):
        if part.lower() == "images":
            parts[index] = "labels"
            return Path(*parts).with_suffix(".txt")
    return image_path.with_suffix(".txt")


def discover_records(
    sources: list[Path],
    source_classes: dict[Path, str] | None = None,
    skip_empty_labels: bool = False,
) -> tuple[list[ImageRecord], list[Path], list[Path]]:
    records: list[ImageRecord] = []
    unknown_images: list[Path] = []
    missing_labels: list[Path] = []
    source_classes = source_classes or {}

    for source in sources:
        if not source.exists():
            raise SystemExit(f"Source folder not found: {source}")
        slug = source_slug(source)
        forced_class = source_classes.get(source.resolve())
        for image_path in sorted(source.rglob("*")):
            if not image_path.is_file() or image_path.suffix.lower() not in IMAGE_EXTENSIONS:
                continue
            class_name = forced_class or infer_class(image_path)
            if class_name is None:
                unknown_images.append(image_path)
                continue
            label_path = label_for_image(image_path)
            if not label_path.exists():
                missing_labels.append(image_path)
                continue
            if skip_empty_labels and not label_path.read_text(encoding="utf-8").strip():
                continue
            records.append(
                ImageRecord(
                    image_path=image_path,
                    label_path=label_path,
                    class_name=class_name,
                    group_key=original_group_key(image_path, class_name),
                    source_slug=slug,
                )
            )

    return records, unknown_images, missing_labels


def split_records(records: list[ImageRecord], val_ratio: float, seed: int) -> dict[str, list[ImageRecord]]:
    groups_by_class: dict[str, dict[str, list[ImageRecord]]] = defaultdict(lambda: defaultdict(list))
    for record in records:
        groups_by_class[record.class_name][record.group_key].append(record)

    result = {"train": [], "val": []}
    rng = random.Random(seed)

    for class_name, groups in groups_by_class.items():
        keys = sorted(groups.keys())
        rng.shuffle(keys)
        val_group_count = max(1, int(round(len(keys) * val_ratio))) if len(keys) > 1 else 0
        val_keys = set(keys[:val_group_count])
        for key in keys:
            split = "val" if key in val_keys else "train"
            result[split].extend(groups[key])

    result["train"].sort(key=lambda record: (record.class_name, record.image_path.name))
    result["val"].sort(key=lambda record: (record.class_name, record.image_path.name))
    return result


def clamp01(value: float) -> float:
    return min(1.0, max(0.0, value))


def convert_label_line(line: str, class_id: int, stats: ConvertStats) -> str | None:
    parts = line.split()
    if not parts:
        return None

    try:
        coords = [float(value) for value in parts[1:]]
    except ValueError:
        stats.skipped_lines += 1
        return None

    if len(coords) == 4:
        x_center, y_center, width, height = (clamp01(value) for value in coords)
        stats.bbox_lines += 1
    elif len(coords) >= 6 and len(coords) % 2 == 0:
        xs = [clamp01(value) for value in coords[0::2]]
        ys = [clamp01(value) for value in coords[1::2]]
        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)
        width = max_x - min_x
        height = max_y - min_y
        x_center = min_x + width / 2.0
        y_center = min_y + height / 2.0
        stats.polygon_lines += 1
    else:
        stats.skipped_lines += 1
        return None

    if width <= 0 or height <= 0:
        stats.skipped_lines += 1
        return None

    return f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"


def convert_label_file(record: ImageRecord, destination: Path, stats: ConvertStats) -> int:
    class_id = CLASS_IDS[record.class_name]
    raw_lines = record.label_path.read_text(encoding="utf-8").splitlines()
    if not raw_lines:
        destination.write_text("", encoding="utf-8")
        stats.empty_labels += 1
        return 0

    converted = []
    for line in raw_lines:
        output = convert_label_line(line, class_id=class_id, stats=stats)
        if output is not None:
            converted.append(output)

    destination.write_text("\n".join(converted) + ("\n" if converted else ""), encoding="utf-8")
    return len(converted)


def prepare_dataset_dir(dataset_dir: Path, clean: bool) -> None:
    if clean:
        for child in ["images", "labels"]:
            path = dataset_dir / child
            if path.exists():
                shutil.rmtree(path)
    for split in ["train", "val"]:
        (dataset_dir / "images" / split).mkdir(parents=True, exist_ok=True)
        (dataset_dir / "labels" / split).mkdir(parents=True, exist_ok=True)


def safe_output_name(record: ImageRecord, index: int) -> str:
    class_prefix = record.class_name.lower()
    clean_stem = re.sub(r"[^A-Za-z0-9_]+", "_", record.image_path.stem).strip("_")
    return f"{class_prefix}_{record.source_slug}_{index:06d}_{clean_stem}{record.image_path.suffix.lower()}"


def write_dataset(splits: dict[str, list[ImageRecord]], dataset_dir: Path, clean: bool) -> tuple[Counter[str], Counter[str], ConvertStats]:
    prepare_dataset_dir(dataset_dir, clean=clean)
    label_counts: Counter[str] = Counter()
    image_counts: Counter[str] = Counter()
    stats = ConvertStats()

    for split, records in splits.items():
        for index, record in enumerate(records):
            out_name = safe_output_name(record, index)
            out_image = dataset_dir / "images" / split / out_name
            out_label = dataset_dir / "labels" / split / Path(out_name).with_suffix(".txt")
            shutil.copy2(record.image_path, out_image)
            converted_count = convert_label_file(record, out_label, stats)
            image_counts[f"{split}:{record.class_name}"] += 1
            if converted_count:
                label_counts[f"{split}:{record.class_name}"] += converted_count

    (dataset_dir / "data.yaml").write_text(DATA_YAML, encoding="utf-8")
    return image_counts, label_counts, stats


def zip_dataset(dataset_dir: Path, zip_path: Path) -> None:
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(dataset_dir.rglob("*")):
            if path.is_file():
                archive.write(path, arcname=Path("dataset") / path.relative_to(dataset_dir))


def print_summary(image_counts: Counter[str], label_counts: Counter[str], stats: ConvertStats) -> None:
    print("\nMerged dataset summary:")
    for split in ["train", "val"]:
        split_images = sum(image_counts[f"{split}:{class_name}"] for class_name in CLASS_NAMES)
        split_labels = sum(label_counts[f"{split}:{class_name}"] for class_name in CLASS_NAMES)
        print(f"  {split}: {split_images} images | {split_labels} boxes")
        for class_name in CLASS_NAMES:
            print(
                f"    {class_name}: "
                f"{image_counts[f'{split}:{class_name}']} images | "
                f"{label_counts[f'{split}:{class_name}']} boxes"
            )

    print("\nLabel conversion:")
    print(f"  bbox lines kept: {stats.bbox_lines}")
    print(f"  polygon lines converted to bbox: {stats.polygon_lines}")
    print(f"  empty label files kept as negatives: {stats.empty_labels}")
    print(f"  skipped malformed lines: {stats.skipped_lines}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Merge Roboflow exports into the app's 4-class YOLO detection dataset.")
    parser.add_argument("--source", action="append", type=Path, help="Roboflow export folder. Repeat for multiple folders.")
    parser.add_argument(
        "--source-class",
        action="append",
        help="Force class for one source, format: path=ClassName. Repeat for multiple folders.",
    )
    parser.add_argument("--dataset-dir", type=Path, default=DEFAULT_DATASET_DIR)
    parser.add_argument("--val-ratio", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--skip-empty-labels", action="store_true", help="Skip images whose YOLO label file has no boxes.")
    parser.add_argument("--zip-output", type=Path, help="Optional zip file to create for Colab upload.")
    args = parser.parse_args()

    if args.val_ratio <= 0 or args.val_ratio >= 1:
        raise SystemExit("--val-ratio must be between 0 and 1")

    sources = [path.resolve() for path in (args.source or DEFAULT_SOURCES)]
    source_classes: dict[Path, str] = {}
    for value in args.source_class or []:
        if "=" not in value:
            raise SystemExit("--source-class must use format: path=ClassName")
        raw_path, raw_class = value.split("=", 1)
        class_name = raw_class.strip()
        if class_name not in CLASS_IDS:
            raise SystemExit(f"Unknown class in --source-class: {class_name}")
        source_classes[Path(raw_path).resolve()] = class_name

    dataset_dir = args.dataset_dir.resolve()
    records, unknown_images, missing_labels = discover_records(
        sources,
        source_classes=source_classes,
        skip_empty_labels=args.skip_empty_labels,
    )

    if unknown_images:
        print("[WARN] Images with unknown class were ignored:")
        for path in unknown_images[:20]:
            print(f"  - {path}")
        if len(unknown_images) > 20:
            print(f"  ... and {len(unknown_images) - 20} more")

    if missing_labels:
        print("[WARN] Images missing label files were ignored:")
        for path in missing_labels[:20]:
            print(f"  - {path}")
        if len(missing_labels) > 20:
            print(f"  ... and {len(missing_labels) - 20} more")

    if not records:
        raise SystemExit("No mergeable image/label records found.")

    discovered_counts = Counter(record.class_name for record in records)
    print("Discovered records:")
    for class_name in CLASS_NAMES:
        print(f"  {class_name}: {discovered_counts[class_name]}")

    splits = split_records(records, val_ratio=args.val_ratio, seed=args.seed)
    image_counts, label_counts, stats = write_dataset(splits, dataset_dir=dataset_dir, clean=args.clean)
    print_summary(image_counts, label_counts, stats)
    print(f"\nCreated dataset at: {dataset_dir}")
    print(f"Data YAML: {dataset_dir / 'data.yaml'}")

    if args.zip_output:
        zip_path = args.zip_output.resolve()
        zip_dataset(dataset_dir, zip_path)
        print(f"Created zip for Colab: {zip_path}")


if __name__ == "__main__":
    main()
