"""
Convert Kaggle gti-upm/leapgestrecog into a YOLO dataset compatible with this app.

This is only a quick trial dataset. LeapGestRecog is a static image
classification dataset, not a natural webcam YOLO detection dataset, so the
script creates approximate hand bounding boxes from the dark background.

Class mapping:
  01_palm, 08_palm_moved -> Xoe_Tay
  03_fist, 04_fist_moved -> Nam_Tay
  06_index               -> Chi_Ngon_Tro
  everything else        -> negative/background image with an empty label

Run:
  python training/05_prepare_leapgestrecog_yolo.py --source leapGestRecog --clean --zip-output dataset_leap_trial.zip
  python training/05_prepare_leapgestrecog_yolo.py --zip leapgestrecog.zip --clean --zip-output dataset_leap_trial.zip
"""

from __future__ import annotations

import argparse
import random
import re
import shutil
import zipfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

import cv2


BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_DATASET_DIR = BASE_DIR / "dataset_leap_trial"
DEFAULT_EXTRACT_DIR = BASE_DIR / "data" / "external" / "leapgestrecog"

CLASS_IDS = {
    "Binh_Thuong": 0,
    "Nam_Tay": 1,
    "Chi_Ngon_Tro": 2,
    "Xoe_Tay": 3,
}

CLASS_NAMES = ["Binh_Thuong", "Nam_Tay", "Chi_Ngon_Tro", "Xoe_Tay"]
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

TARGET_CLASS_BY_FOLDER = {
    "01_palm": "Xoe_Tay",
    "08_palm_moved": "Xoe_Tay",
    "03_fist": "Nam_Tay",
    "04_fist_moved": "Nam_Tay",
    "06_index": "Chi_Ngon_Tro",
}

DATA_YAML = """# Generated by training/05_prepare_leapgestrecog_yolo.py
path: /content/dataset
train: images/train
val: images/val

names:
  0: Binh_Thuong
  1: Nam_Tay
  2: Chi_Ngon_Tro
  3: Xoe_Tay
"""


@dataclass(frozen=True)
class Record:
    image_path: Path
    source_class: str
    target_class: str | None
    subject: str


def normalize_folder_name(value: str) -> str:
    return value.strip().lower().replace("-", "_").replace(" ", "_")


def extract_zip(zip_path: Path, extract_dir: Path, clean: bool) -> Path:
    if clean and extract_dir.exists():
        shutil.rmtree(extract_dir)
    extract_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, "r") as archive:
        archive.extractall(extract_dir)
    return extract_dir


def find_dataset_root(source: Path) -> Path:
    if not source.exists():
        raise SystemExit(f"Source not found: {source}")

    candidates = []
    for path in [source, *source.rglob("*")]:
        if not path.is_dir():
            continue
        child_names = {normalize_folder_name(child.name) for child in path.iterdir() if child.is_dir()}
        if {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09"}.issubset(child_names):
            candidates.append(path)
        if {"01_palm", "03_fist", "06_index", "08_palm_moved"}.issubset(child_names):
            candidates.append(path.parent)

    if not candidates:
        raise SystemExit(
            "Could not find LeapGestRecog structure. Expected folders like "
            "leapGestRecog/00/01_palm/*.png"
        )
    return sorted(candidates, key=lambda p: len(str(p)))[0]


def discover_records(root: Path, include_negative: bool, max_per_source_class: int | None, seed: int) -> list[Record]:
    by_source_class: dict[str, list[Record]] = defaultdict(list)
    for image_path in sorted(root.rglob("*")):
        if not image_path.is_file() or image_path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue

        source_class = normalize_folder_name(image_path.parent.name)
        target_class = TARGET_CLASS_BY_FOLDER.get(source_class)
        if target_class is None and not include_negative:
            continue

        subject = image_path.parent.parent.name
        by_source_class[source_class].append(
            Record(
                image_path=image_path,
                source_class=source_class,
                target_class=target_class,
                subject=subject,
            )
        )

    rng = random.Random(seed)
    records: list[Record] = []
    for source_class, items in sorted(by_source_class.items()):
        rng.shuffle(items)
        if max_per_source_class is not None:
            items = items[:max_per_source_class]
        records.extend(items)
    records.sort(key=lambda item: (item.target_class or "negative", item.source_class, item.image_path.name))
    return records


def split_records(records: list[Record], val_ratio: float, seed: int) -> dict[str, list[Record]]:
    groups: dict[str, list[Record]] = defaultdict(list)
    for record in records:
        key = f"{record.target_class or 'negative'}:{record.source_class}:{record.subject}"
        groups[key].append(record)

    rng = random.Random(seed)
    keys = sorted(groups)
    rng.shuffle(keys)
    val_count = max(1, int(round(len(keys) * val_ratio))) if len(keys) > 1 else 0
    val_keys = set(keys[:val_count])

    splits = {"train": [], "val": []}
    for key in keys:
        split = "val" if key in val_keys else "train"
        splits[split].extend(groups[key])

    for split in splits:
        splits[split].sort(key=lambda item: (item.target_class or "negative", item.source_class, item.image_path.name))
    return splits


def bbox_from_dark_background(image_path: Path, padding: float) -> tuple[float, float, float, float] | None:
    image = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    if image is None:
        return None

    # LeapGestRecog images usually have a dark background and bright hand.
    blurred = cv2.GaussianBlur(image, (5, 5), 0)
    _, mask = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    contour = max(contours, key=cv2.contourArea)
    if cv2.contourArea(contour) < 20:
        return None

    x, y, w, h = cv2.boundingRect(contour)
    image_h, image_w = image.shape[:2]
    pad_x = int(round(w * padding))
    pad_y = int(round(h * padding))
    x1 = max(0, x - pad_x)
    y1 = max(0, y - pad_y)
    x2 = min(image_w, x + w + pad_x)
    y2 = min(image_h, y + h + pad_y)

    box_w = max(1, x2 - x1)
    box_h = max(1, y2 - y1)
    x_center = (x1 + box_w / 2.0) / image_w
    y_center = (y1 + box_h / 2.0) / image_h
    return x_center, y_center, box_w / image_w, box_h / image_h


def prepare_output(dataset_dir: Path, clean: bool) -> None:
    if clean and dataset_dir.exists():
        shutil.rmtree(dataset_dir)
    for split in ["train", "val"]:
        (dataset_dir / "images" / split).mkdir(parents=True, exist_ok=True)
        (dataset_dir / "labels" / split).mkdir(parents=True, exist_ok=True)


def safe_name(record: Record, index: int) -> str:
    prefix = record.target_class.lower() if record.target_class else "negative"
    stem = re.sub(r"[^A-Za-z0-9_]+", "_", record.image_path.stem).strip("_")
    return f"{prefix}_{record.source_class}_{record.subject}_{index:06d}_{stem}{record.image_path.suffix.lower()}"


def write_dataset(splits: dict[str, list[Record]], dataset_dir: Path, clean: bool, padding: float) -> Counter[str]:
    prepare_output(dataset_dir, clean=clean)
    counts: Counter[str] = Counter()

    for split, records in splits.items():
        for index, record in enumerate(records):
            out_name = safe_name(record, index)
            out_image = dataset_dir / "images" / split / out_name
            out_label = dataset_dir / "labels" / split / Path(out_name).with_suffix(".txt")

            shutil.copy2(record.image_path, out_image)
            if record.target_class is None:
                out_label.write_text("", encoding="utf-8")
                counts[f"{split}:negative"] += 1
                continue

            bbox = bbox_from_dark_background(record.image_path, padding=padding)
            if bbox is None:
                out_label.write_text("", encoding="utf-8")
                counts[f"{split}:failed_bbox"] += 1
                continue

            class_id = CLASS_IDS[record.target_class]
            out_label.write_text(
                f"{class_id} {bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}\n",
                encoding="utf-8",
            )
            counts[f"{split}:{record.target_class}"] += 1

    (dataset_dir / "data.yaml").write_text(DATA_YAML, encoding="utf-8")
    return counts


def zip_dataset(dataset_dir: Path, zip_output: Path) -> None:
    if zip_output.exists():
        zip_output.unlink()
    with zipfile.ZipFile(zip_output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(dataset_dir.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(dataset_dir.parent))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare LeapGestRecog as a YOLO trial dataset.")
    parser.add_argument("--source", type=Path, help="Extracted LeapGestRecog folder.")
    parser.add_argument("--zip", type=Path, help="Path to leapgestrecog.zip.")
    parser.add_argument("--extract-dir", type=Path, default=DEFAULT_EXTRACT_DIR)
    parser.add_argument("--dataset-dir", type=Path, default=DEFAULT_DATASET_DIR)
    parser.add_argument("--zip-output", type=Path, default=BASE_DIR / "dataset_leap_trial.zip")
    parser.add_argument("--val-ratio", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-per-source-class", type=int, default=600)
    parser.add_argument("--padding", type=float, default=0.08)
    parser.add_argument("--no-negative", action="store_true", help="Do not include non-target gesture folders as empty labels.")
    parser.add_argument("--clean", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.zip:
        source = extract_zip(args.zip, args.extract_dir, clean=args.clean)
    elif args.source:
        source = args.source
    else:
        raise SystemExit("Pass either --zip leapgestrecog.zip or --source leapGestRecog")

    root = find_dataset_root(source)
    records = discover_records(
        root,
        include_negative=not args.no_negative,
        max_per_source_class=args.max_per_source_class,
        seed=args.seed,
    )
    if not records:
        raise SystemExit(f"No images found under {root}")

    splits = split_records(records, val_ratio=args.val_ratio, seed=args.seed)
    counts = write_dataset(splits, dataset_dir=args.dataset_dir, clean=args.clean, padding=args.padding)
    zip_dataset(args.dataset_dir, args.zip_output)

    print(f"Source root: {root}")
    print(f"Dataset: {args.dataset_dir}")
    print(f"Zip: {args.zip_output}")
    print("Counts:")
    for key, value in sorted(counts.items()):
        print(f"  {key}: {value}")
    print("")
    print("Train on Colab after upload:")
    print("  unzip dataset_leap_trial.zip -d /content")
    print("  yolo task=detect mode=train model=yolov8n.pt data=/content/dataset_leap_trial/data.yaml epochs=50 imgsz=640")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
